---
# Source: temporal/templates/server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: temporal-history
        image: "test.dunamu.io/app"
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_PASSWORD
          value: 896fy1e1!$yq7u5ba!@sady
